name: docker-image-sync
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 01 * * 0'
  
jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 镜像同步配置处理
      run: |
        sed -i 's/HUB_PASSWORD/${{ secrets.HUB_PASSWORD }}/g' config.json
        
    - name: 下载image-sync工具包
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.3.1/image-syncer-v1.3.1-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.3.1-linux-amd64.tar.gz
      
    - name: 执行同步镜像
      run: |
        ./image-syncer --proc=100 --config=config.json --retries=5
